version: '3.8'
services:
  elastic:
    ports:
      - 9200:9200

  kibana:
    container_name: core_search_ui
    image: docker.elastic.co/kibana/kibana:8.5.2
    environment:
      - ELASTICSEARCH_HOSTS=http://core_search:9200
    networks:
      - gamefi-search
    depends_on:
      - elastic
    ports:
      - 5601:5601

networks:
  gamefi-search:
    driver: bridge
