version: '3.8'
services:
  search:
    container_name: search
    image: search
    networks:
      - gamefi-search-network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - elastic
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: unless-stopped

  elastic:
    container_name: core_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx1g"
      - 'discovery.type=single-node'
    networks:
      - gamefi-search-network
      
networks:
  gamefi-search-network:
    driver: bridge